apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-orders-deployment
  labels:
    app: webapp-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-orders
  template:
    metadata:
      labels:
        app: webapp-orders
    spec:
      containers:
        - name: webapp-orders
          image: webapp-orders:v1
          imagePullPolicy: Never # this is used for minikube mode only
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-orders-load-balancer
  labels:
    app: webapp-orders
spec: 
  type: LoadBalancer
  selector: 
    app: webapp-orders
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
