apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: bff-orders-dev
nameSuffix: -dev
resources:
  - ../../base
configMapGenerator:
  - name: bff-orders-configmap
    behavior: replace
    literals:
      - NODE_ENV="development"
      - ORDERS_SERVICE_URL="http://127.0.0.1:8001"
