apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bff-orders.yaml
configMapGenerator:
  - name: bff-orders-configmap
    literals:
      - NODE_ENV="development"
      - ORDERS_SERVICE_URL="http://127.0.0.1:8001"