apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: bff-orders-prod
nameSuffix: -prod
resources:
  - ../../base
configMapGenerator:
  - name: bff-orders-configmap
    behavior: replace
    literals:
      - NODE_ENV="production"
      - ORDERS_SERVICE_URL="http://ms-orders-service"
