apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-orders-deployment
  labels:
    app: ms-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-orders
  template:
    metadata:
      labels:
        app: ms-orders
    spec:
      containers:
        - name: ms-orders
          image: ms-orders:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: ms-orders-configmap
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_URL
---
apiVersion: v1
kind: Service
metadata:
  name: ms-orders-service
  labels:
    app: ms-orders
spec: 
  type: ClusterIP
  selector: 
    app: ms-orders
  ports:
    - port: 8001
      targetPort: 8001