apiVersion: apps/v1
kind: Deployment

metadata:
  name: ms-orders-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      service: ms-orders

  template:
    metadata:
      labels:
        service: ms-orders
    spec:
      containers:
      - name: ms-orders
        image: ms-orders:v1
        imagePullPolicy: Never
        ports:
          - containerPort: 8001
        env:
          - name: NODE_ENV
            value: production
          - name: DB_HOST
            value: mydb.c0rpbzb5tvzy.ap-southeast-1.rds.amazonaws.com
          - name: DB_PORT
            value: "3306"
          - name: DB_SCHEMA
            value: test
          - name: DB_USERNAME
            value: admin
          - name: DB_PASSWORD
            value: V16#u123
          - name: RABBITMQ_URL
            value: amqps://saoipjon:ukZdlmTUqwxSBn8RoeWA4XdWxRFUfgfS@armadillo.rmq.cloudamqp.com/saoipjon
          - name: RABBITMQ_QUEUE
            value: test