apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ms-payments-dev
nameSuffix: -prod
resources:
  - ../../base
configMapGenerator:
  - name: ms-payments-configmap
    behavior: replace
    literals:
      - NODE_ENV="production"
      - RABBITMQ_QUEUE="test"
secretGenerator:
  - name: rabbitmq-secret
    literals:
      - RABBITMQ_URL="amqps://saoipjon:ukZdlmTUqwxSBn8RoeWA4XdWxRFUfgfS@armadillo.rmq.cloudamqp.com/saoipjon"
